version: "3"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      args:
        WORKDIR: /app
    image: ${DOCKER_USERNAME}/live-chat-backend
    environment:
      - PORT=$BACKEND_PORT
      - FRONTEND_HOST
    ports:
      - $BACKEND_PORT:$BACKEND_PORT
    networks:
      - the-network
    volumes:
      - ./backend:/app/

  backend-test:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
      args:
        WORKDIR: /app
    image: ${DOCKER_USERNAME}/live-chat-backend-test
    volumes:
      - ./backend:/app/

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: ${DOCKER_USERNAME}/live-chat-frontend
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_HOST
    ports:
      - 3000:3000
    networks:
      - the-network
    volumes:
      - ./frontend:/app/

networks:
  the-network:
    driver: bridge